services:
    scraper:
      image: data_scraper
      container_name: scraper
      build: .
      volumes:
        - ./data_scraping/bus_data.db:/app/bus_data.db
    # trainer:
    #   image: nn_trainer
    #   container_name: trainer
    #   context: .
    #   dockerfile: Dockerfile.training